version: '3.9'

networks:
  uca-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local

services:
  mongo:
    image: mongo:7.0.1-jammy
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mongo
