version: '3.9'

services:
  cudemy:
    container_name: cudemy
    build:
      context: ./
      dockerfile: docker/cudemy/Dockerfile
      target: base
    volumes:
      - ./.env:/data/app/.env:ro
      - ./src/:/data/app/src/:ro
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=development
    restart: on-failure
