import { Controller, Post, UseGuards, Get, HttpCode } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiOkResponse, ApiOperation, ApiTags, ApiUnauthorizedResponse } from '@nestjs/swagger';

import { AuthAccessToken, AuthUser } from '#auth/auth-user.decorator';
import { AuthService } from '#auth/auth.service';
import { LoginDto, LoginResponseDto } from '#auth/dto/login.dto';
import { UserPayloadDto } from '#auth/dto/verify.dto';
import { JwtAuthGuard, LocalAuthGuard } from '#auth/guard';

@Controller('auth')
@ApiTags('auth')
@ApiUnauthorizedResponse({ status: 401, description: 'Unauthorized' })
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @Post('login')
  @HttpCode(200)
  @UseGuards(LocalAuthGuard)
  @ApiBody({ type: LoginDto, description: 'Login payload' })
  @ApiOkResponse({ status: 200, description: 'Login successfully', type: LoginResponseDto })
  @ApiOperation({
    summary: 'Login user',
    description: "It can login using the existing user's email and TID generated by CUdemy.",
    operationId: 'login',
  })
  async login(@AuthUser() authUser: UserPayloadDto): Promise<LoginResponseDto> {
    return await this.authService.login(authUser);
  }

  @Post('verify')
  @HttpCode(200)
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOkResponse({ status: 200, description: 'Verify successfully', type: UserPayloadDto })
  @ApiOperation({
    summary: 'Verify access token',
    description: 'It can verify the validity of the access token.',
    operationId: 'verify',
  })
  getJwtAuth(@AuthUser() authUser: UserPayloadDto): UserPayloadDto {
    return authUser;
  }

  @Get('logout')
  @HttpCode(200)
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOkResponse({ status: 200, description: 'Logout successfully', type: UserPayloadDto })
  @ApiOperation({
    summary: 'Logout user',
    description: 'It can logout current logged in user session.',
    operationId: 'logout',
  })
  async logout(
    @AuthUser()
    authUser: UserPayloadDto,
    @AuthAccessToken() accessToken: string,
  ): Promise<UserPayloadDto> {
    return await this.authService.logout(authUser, accessToken);
  }
}
